# Generated by Django 3.2.11 on 2023-01-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScoreCenterShop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('image', models.FileField(null=True, upload_to='products')),
            ],
        ),
    ]
